### ISSUE TITLE
Add a CLI

### ISSUE THREAD

**Issue by physikerwelt** [TU-Berlin/project-mlp#4]
For developing and testing it would be great to be able to use mlp independent of stratosphere from the commandline like
```
mlp subcommand filename.ext
```
the following subcommands would be nice
* list-identifiers
* count formulae
* count identifiers
* extract definitioins with a methoid parameter that could be rule-based or statistical
* show pos-tags

1-4 should be run if subcommand is empty

**Comment by physikerwelt** [comment]
@alexeygrigorev I realized that you implemented a lot of tests. How much work would it be to develop some very simple cli support? I would need that for some explorary analysis.

**Comment by alexeygrigorev** [comment]
There's already some CLI support, but not in the form you want. I replied in a different thread and gave an example of how yo use it, but I see that it's something different. 

This one would require some re-writing of the code

**Comment by alexeygrigorev** [comment]
@physikerwelt, are you already doing it?

**Comment by physikerwelt** [comment]
I'm trying;-)

On Sun, Sep 27, 2015 at 3:11 PM, Alexey Grigorev <notifications@github.com>
wrote:

> @physikerwelt <https://github.com/physikerwelt>, are you already doing
> it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TU-Berlin/project-mlp/issues/4#issuecomment-143549315>
> .
>



-- 
Moritz Schubotz
TU Berlin, Fakultät IV
DIMA - Sekr. EN7
Raum EN742
Einsteinufer 17
D-10587 Berlin
Germany

Tel.: +49 30 314 22784
Mobil.: +49 1578 047 1397
Fax:  +49 30 314 21601
E-Mail: schubotz@tu-berlin.de
Skype: Schubi87
ICQ: 200302764
Msn: Moritz@Schubotz.de

**Comment by alexeygrigorev** [comment]
I have added basic CLI support. 

- `mlp` will apply the algorithm to a wiki dump
- To apply it to a single wiki article, use `extract` 
- Commands `count` and `list` are not yet implemented. 
- use `help` to see all available commands

Example. Suppose you want to extract relations from [Linear regression](https://en.wikipedia.org/wiki/Linear_regression). Save the wiki markup to `linear_regression.txt` and then do 

`java mlp.Main extract  -in "C:/tmp/mlp/linear_regression.txt"`

This should output all extracted relations to stdout.

**Comment by physikerwelt** [comment]
I think what we have is "good enough"
